apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-driver
  namespace: spark
  labels: {}
  annotations: {}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-external
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-executor
  namespace: spark
  labels: {}
  annotations: {}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-external